# Link repository with Travis CI
# https://travis-ci.org/

# Whitelist gh-pages branch
branches:
  only:
    - master

# Set the language
language: bash

os: osx

env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/usr/bin/:$PATH
    - PATH=/Library/TeX/texbin:$PATH

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  # - "2.7"
  # - "3.5"
  # - "3.6"
  - "3.7"
  - "3.8"

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Make python venv
  - conda create -n phd python=${PYTHON_VERSION} pandoc
  - conda activate phd
  # The install of mactex takes a long time
  - brew install --cask mactex
  - sudo tlmgr update --self
  # Installs both python and texlive dependencies
  - make install

# Attempt to create all document output types
script:
  - make help
  - make all
  - cat pandoc.pdf.log
  - cat pandoc.tex.log
  - cat pandoc.html.log
  - cat pandoc.docx.log
